### ISSUE TITLE
Bungee error spamming

### ISSUE THREAD

**Issue by Eufranio** [DevLeoko/AdvancedBan#14]
Error:

```
13:28:33 [SEVERE] Oct 02, 2016 1:28:33 PM net.md_5.bungee.event.EventBus post
WARNING: Error dispatching event ChatEvent(super=TargetedEvent(sender=Uneven_Gamer, receiver=net.md_5.bungee.ServerConnection@409fbdaf), cancelled=false, message=nao ;-;) to listener me.leoko.advancedban.bungee.listener.ChatListenerBungee@1827a871
java.lang.ClassCastException: com.google.gson.JsonNull cannot be cast to com.google.gson.JsonObject
    at me.leoko.advancedban.bungee.BungeeMethods.parseJSON(BungeeMethods.java:266)
    at me.leoko.advancedban.manager.UUIDManager.askAPI(UUIDManager.java:81)
    at me.leoko.advancedban.manager.UUIDManager.getInitialUUID(UUIDManager.java:30)
    at me.leoko.advancedban.manager.UUIDManager.getUUID(UUIDManager.java:57)
    at me.leoko.advancedban.bungee.BungeeMethods.callChat(BungeeMethods.java:223)
    at me.leoko.advancedban.bungee.listener.ChatListenerBungee.onChat(ChatListenerBungee.java:18)
    at sun.reflect.GeneratedMethodAccessor27.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)
    at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:119)
    at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:77)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:280)
    at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:396)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:248)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:266)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:345)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:366)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:352)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:883)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:389)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:305)
    at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:140)
    at java.lang.Thread.run(Thread.java:745)
```

I'm using last AdvancedBan from Spigot in my bungee, and using latest BungeeCord from HexagonMC.

**Comment by DevLeoko** [comment]
Ya this seems to be a problem with you UUID-Fetcher Settings try to change them to internal or switch off the UUID-Fatcher completely.

**Comment by Eufranio** [comment]
What would you suggest, I run a cracked server, but I have a plugins to separate cracked users of premium users, then they join with cracked/premium UNIDOS respectively. Could you implement compatibility with it?

**Comment by DevLeoko** [comment]
Then just disable the UUID-Fetcher

**Comment by Eufranio** [comment]
And leave the function useless?

**Comment by DevLeoko** [comment]
which function?

**Comment by Eufranio** [comment]
UUID-Fetcher, it retrieves offline players UUID, right?

**Comment by DevLeoko** [comment]
ya and from online players

**Comment by Eufranio** [comment]
then...

**Comment by DevLeoko** [comment]
I don't really get what you want just go into the config.yml of AdvancedBan and turn off the UUID-Fetcher.

**Comment by dutchy1001** [comment]
This can be closed as the UUID fetcher for cracked servers must be set to` enable: false`.

I presume the mistake made here is the when players are **offline** it still can fetch the UUID for warning, muting or banning not meaning the UUID for a **cracked** client can be fetched to do the same. 
Cracked player UUID's are useless as they can change from login to login (as far I understand) so it only bans by name or IP.

**Comment by DevLeoko** [comment]
Ya also the error is avoided in one of the last commits and replaced with a slim failed-to-fetch message
