### ISSUE TITLE
An unexpected error has ocurred executing an Statement in the database

### ISSUE THREAD

**Issue by leventinio** [DevLeoko/AdvancedBan#167]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_

Neuste Version
 
 
_What kind of server do you have (`Bungeecord/single server`)?_

BungeeCord
 
 
_What server version (/version) are you using?_

Neuste Bungeecord Version

_Please provide the EXACT steps required to reproduce the problem..._
1.
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here._

17:26:26 [INFO] [Xilef4002] <-> DownstreamBridge <-> [lobby] has disconnected
17:26:33 [INFO] [AdvancedBan] An unexpected error has ocurred executing an Statement in the database
Please check the debug.log file in the plugin's folder and report thiserror in: https://github.com/DevLeoko/AdvancedBan/issues
17:26:33 [SEVERE] Jan 19, 2018 5:26:33 PM net.md_5.bungee.event.EventBus post
WARNING: Error dispatching event ChatEvent(super=TargetedEvent(sender=Xilef4002, receiver=net.md_5.bungee.ServerConnection@758938fd), cancelled=false, message=.) to listener me.leoko.advancedban.bungee.listener.ChatListenerBungee@3c321bdb
java.lang.NullPointerException
    at me.leoko.advancedban.manager.PunishmentManager.getPunishments(PunishmentManager.java:107)
    at me.leoko.advancedban.manager.PunishmentManager.getMute(PunishmentManager.java:171)
    at me.leoko.advancedban.bungee.BungeeMethods.callChat(BungeeMethods.java:246)
    at me.leoko.advancedban.bungee.listener.ChatListenerBungee.onChat(ChatListenerBungee.java:22)
    at sun.reflect.GeneratedMethodAccessor16.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19)
    at net.md_5.bungee.event.EventBus.post(EventBus.java:46)
    at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:377)
    at net.md_5.bungee.connection.UpstreamBridge.handle(UpstreamBridge.java:137)
    at net.md_5.bungee.protocol.packet.Chat.handle(Chat.java:50)
    at net.md_5.bungee.netty.HandlerBoss.channelRead(HandlerBoss.java:103)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
    at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:284)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
    at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1359)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
    at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
    at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:935)
    at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:800)
    at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:404)
    at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:304)
    at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
    at java.lang.Thread.run(Thread.java:748)

17:27:52 [WARNING] Event ChatEvent(super=TargetedEvent(sender=Xilef4002, receiver=net.md_5.bungee.ServerConnection@758938fd), cancelled=false, message=und wie kann man nen Job auswählen?) took 369,486,581ns to process!
17:28:37 [INFO] Xilef4002 executed command: /l
17:28:37 [INFO] [Xilef4002] <-> ServerConnector [lobby] has connected

_Add any additional information below._

**Comment by DevLeoko** [comment]
In the version you have been using, some error messages have not been logged.
As this makes it impossible for us to help this issue will be closed.

You can download the newest build here: http://v.skamps.eu/jenkins/job/AdvancedBanV2/26/
In this build, all errors will be logged to the AdvancedBan logs.

If you get the same issue again with the newer version, make sure to reopen the issue and paste the additional information. I'm sorry for the inconvenience.
