### ISSUE TITLE
[MC 1.12.2] latest.log + MySQL Error

### ISSUE THREAD

**Issue by MrArtem1337** [DevLeoko/AdvancedBan#245]
What version of AdvancedBan are you using?

> **2.1.5-Release**

What kind of server do you have single server?

> **PaperSpigot single server**

What server version are you using?

> **This server is running Paper version git-Paper-1524 (MC: 1.12.2) (Implementing API version 1.12.2-R0.1-SNAPSHOT)**
> **Previous version: git-Paper-1415 (MC: 1.12.2)**

Any error/log post it through pastebin.com and link it here.

> https://pastebin.com/Q2nGeVH0

**Comment by Beelzebu** [comment]
The paste is private

**Comment by MrArtem1337** [comment]
Try this https://pastebin.com/V4Uz0igD

**Comment by DevLeoko** [comment]
"Please check the plugins/AdvancedBan/logs/latest.log file"
Check that file and post the error message found there

**Comment by MrArtem1337** [comment]
> Please check the plugins/AdvancedBan/logs/latest.log file and report thiserror in: https://github.com/DevLeoko/AdvancedBan/issues
[08:50:08] Query: 
INSERT INTO `Punishments` (`name`, `uuid`, `reason`, `operator`, `punishmentType`, `start`, `end`, `calculation`) VALUES (?, ?, ?, ?, ?, FROM_UNIXTIME(? * 0.001), FROM_UNIXTIME(? * 0.001), ?)
[08:50:08] java.sql.SQLException: Incorrect string value: '\xD0\xBC\xD0\xB5\xD1\x88...' for column 'reason' at row 1
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:210)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:186)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:182)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:165)
	at me.leoko.advancedban.utils.Punishment.create(Punishment.java:106)
	at me.leoko.advancedban.manager.CommandManager.lambda$onCommand$0(CommandManager.java:126)
	at me.leoko.advancedban.manager.CommandManager$$Lambda$330/1542852207.run(Unknown Source)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:63)
	at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
	at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

[08:50:08] !! No able to update ID of punishment! Please restart the server to resolve this issue!
[08:50:08] !! Failed at: Punishment{id=-1, name='olpon189', uuid='olpon189', reason='мешал', operator='vagu', start=1535439008920, end=-1, calculation='null', type=BAN}

**Comment by MrArtem1337** [comment]
HEEEY I AM HERE

**Comment by Beelzebu** [comment]
Try using the release published in spigot, you're using a development build

**Comment by MrArtem1337** [comment]
Not working!

**Comment by DevLeoko** [comment]
Please send the new error message with the stable build from spigot and explain how exactly this can be reproduced
