### ISSUE TITLE
PlayerCommandPreprocessEvent

### ISSUE THREAD

**Issue by Kiepi** [DevLeoko/AdvancedBan#256]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.1.5-RELEASE
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Spigot 1.12.2
 
_What server version (/version) are you using?_
1.12.2 +Protocol Support

[23:24:15 ERROR]: Could not pass event PlayerCommandPreprocessEvent to AdvancedBan v2.1.5-RELEASE
org.bukkit.event.EventException: null
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:306) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:500) [server.jar:git-Spigot-dcd1643-e60fc34]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:485) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerConnection.handleCommand(PlayerConnection.java:1391) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerConnection.a(PlayerConnection.java:1234) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:45) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PacketPlayInChat.a(PacketPlayInChat.java:1) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.PlayerConnectionUtils$1.run(SourceFile:13) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_172]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_172]
at net.minecraft.server.v1_12_R1.SystemUtils.a(SourceFile:46) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.D(MinecraftServer.java:748) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.DedicatedServer.D(DedicatedServer.java:406) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.C(MinecraftServer.java:679) [server.jar:git-Spigot-dcd1643-e60fc34]
at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:577) [server.jar:git-Spigot-dcd1643-e60fc34]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_172]
Caused by: java.lang.IllegalStateException: RevokePunishmentEvent cannot be triggered asynchronously from inside synchronized code.
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:477) ~[server.jar:git-Spigot-dcd1643-e60fc34]
at me.leoko.advancedban.bukkit.BukkitMethods.callRevokePunishmentEvent(BukkitMethods.java:352) ~[?:?]
at me.leoko.advancedban.utils.Punishment.delete(Punishment.java:208) ~[?:?]
at me.leoko.advancedban.manager.PunishmentManager.getPunishments(PunishmentManager.java:99) ~[?:?]
at me.leoko.advancedban.manager.PunishmentManager.getMute(PunishmentManager.java:171) ~[?:?]
at me.leoko.advancedban.bukkit.BukkitMethods.callCMD(BukkitMethods.java:238) ~[?:?]
at me.leoko.advancedban.bukkit.listener.CommandListener.onCommand(CommandListener.java:15) ~[?:?]
at sun.reflect.GeneratedMethodAccessor121.invoke(Unknown Source) ~[?:?]
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_172]
at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_172]
at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:302) ~[server.jar:git-Spigot-dcd1643-e60fc34]
... 16 more

**Comment by DevLeoko** [comment]
Should be solved with the newest version: https://www.spigotmc.org/resources/advancedban.8695/update?update=321631
