### ISSUE TITLE
Mysql error

### ISSUE THREAD

**Issue by SirKappa** [DevLeoko/AdvancedBan#377]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
**2.2.0**
 
_What kind of server do you have (`Bungeecord/single server`)?_
**Single server**
 
_What server version (/version) are you using?_
**Paper 1.12.2** 

[22:53:56] An unexpected error has occurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report this error in: https://github.com/DevLeoko/AdvancedBan/issues
[22:53:56] Query:
INSERT INTO `Punishments` (`name`, `uuid`, `reason`, `operator`, `punishmentType`, `start`, `end`, `calculation`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
[22:53:56] java.sql.SQLException: Incorrect string value: '\xD0\x9D\xD0\xB0\xD1\x80...' for column 'reason' at row 1
at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3973)
at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3909)
at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2527)
at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2680)
at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2484)
at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1858)
at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1197)
at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:122)
at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:107)
at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:92)
at me.leoko.advancedban.utils.Punishment.create(Punishment.java:117)
at me.leoko.advancedban.utils.Punishment.create(Punishment.java:46)
at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:72)
at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:18)
at me.leoko.advancedban.utils.Command.execute(Command.java:404)
at me.leoko.advancedban.manager.CommandManager.lambda$onCommand$0(CommandManager.java:46)
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftTask.run(CraftTask.java:64)
at org.bukkit.craftbukkit.v1_12_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:52)
at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)

**Comment by AllRife** [comment]
Hi Dev!
I found one of solving this problem
There is a problem with encoding tables on database (MySQL).
Problem: If the reason in en - its working, but, if it in Russian (for example) (unicode) - there is an error and data didn't save.
Solving problem: Change encoding all tables of plugin to 'utf8mb4_general_ci'
Sincerely yours,
AllRife :3

**Comment by DevLeoko** [comment]
Alright, thanks for the update.
I'll leave this issue open though as a reminder for us to check the encoding settings and ensure that on our end everything is set correctly.

**Comment by SirKappa** [comment]
[05:05:28] Failed enabling database-manager...
[05:05:28] me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Unsupported character encoding 'utf8mb4_general_ci'.
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:595)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:581)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at me.leoko.advancedban.utils.DynamicDataSource.generateDataSource(DynamicDataSource.java:37)
	at me.leoko.advancedban.manager.DatabaseManager.setup(DatabaseManager.java:51)
	at me.leoko.advancedban.Universal.setup(Universal.java:62)
	at me.leoko.advancedban.bukkit.BukkitMain.onEnable(BukkitMain.java:23)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Unsupported character encoding 'utf8mb4_general_ci'.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionPropertiesImpl.postInitialization(ConnectionPropertiesImpl.java:2549)
	at com.mysql.jdbc.ConnectionPropertiesImpl.initializeProperties(ConnectionPropertiesImpl.java:2519)
	at com.mysql.jdbc.ConnectionImpl.initializeDriverProperties(ConnectionImpl.java:3141)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:760)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:386)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:330)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	... 17 more

[05:05:28] An unexpected error has occurred connecting to the database
Check if your MySQL data is correct and if your MySQL-Server is online
Please check the plugins/AdvancedBan/logs/latest.log file and report this error in: https://github.com/DevLeoko/AdvancedBan/issues
[05:05:28] java.lang.NullPointerException
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:111)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:107)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:92)
	at me.leoko.advancedban.manager.PunishmentManager.setup(PunishmentManager.java:38)
	at me.leoko.advancedban.Universal.setup(Universal.java:69)
	at me.leoko.advancedban.bukkit.BukkitMain.onEnable(BukkitMain.java:23)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:316)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugin(CraftServer.java:395)
	at org.bukkit.craftbukkit.v1_12_R1.CraftServer.enablePlugins(CraftServer.java:344)
	at net.minecraft.server.v1_12_R1.MinecraftServer.t(MinecraftServer.java:442)
	at net.minecraft.server.v1_12_R1.MinecraftServer.l(MinecraftServer.java:403)
	at net.minecraft.server.v1_12_R1.MinecraftServer.a(MinecraftServer.java:341)
	at net.minecraft.server.v1_12_R1.DedicatedServer.init(DedicatedServer.java:289)
	at net.minecraft.server.v1_12_R1.MinecraftServer.run(MinecraftServer.java:616)
	at java.lang.Thread.run(Thread.java:748)

**Comment by SirKappa** [comment]
Properties: 'verifyServerCertificate=false&useSSL=false&useUnicode=true&characterEncoding=utf8mb4_general_ci'

**Comment by SirKappa** [comment]
Sorry, I misunderstood. I changed the encoding of tables in the database, it worked, thank you, the question is no longer relevant.

**Comment by DevLeoko** [comment]
I'll leave this issue open though as a reminder for us to check the encoding settings and ensure that on our end everything is set correctly.

**Comment by minecraftdan1234** [comment]
```
[12:26:18] An unexpected error has occurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report this error in: https://github.com/DevLeoko/AdvancedBan/issues
[12:26:18] Query: 
INSERT INTO `PunishmentHistory` (`name`, `uuid`, `reason`, `operator`, `punishmentType`, `start`, `end`, `calculation`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
[12:26:18] com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'reason' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1251)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:122)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:107)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:92)
	at me.leoko.advancedban.utils.Punishment.create(Punishment.java:111)
	at me.leoko.advancedban.utils.Punishment.create(Punishment.java:46)
	at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:72)
	at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:18)
	at me.leoko.advancedban.utils.Command.execute(Command.java:404)
	at me.leoko.advancedban.manager.CommandManager.lambda$onCommand$0(CommandManager.java:46)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[12:26:18] An unexpected error has occurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report this error in: https://github.com/DevLeoko/AdvancedBan/issues
[12:26:18] Query: 
INSERT INTO `Punishments` (`name`, `uuid`, `reason`, `operator`, `punishmentType`, `start`, `end`, `calculation`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
[12:26:18] com.mysql.jdbc.MysqlDataTruncation: Data truncation: Data too long for column 'reason' at row 1
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3931)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:2524)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2675)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2465)
	at com.mysql.jdbc.PreparedStatement.executeInternal(PreparedStatement.java:1912)
	at com.mysql.jdbc.PreparedStatement.execute(PreparedStatement.java:1251)
	at com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:122)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:107)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:92)
	at me.leoko.advancedban.utils.Punishment.create(Punishment.java:115)
	at me.leoko.advancedban.utils.Punishment.create(Punishment.java:46)
	at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:72)
	at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:18)
	at me.leoko.advancedban.utils.Command.execute(Command.java:404)
	at me.leoko.advancedban.manager.CommandManager.lambda$onCommand$0(CommandManager.java:46)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:63)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

[12:26:18] !! Not able to update ID of punishment! Please restart the server to resolve this issue!
[12:26:18] !! Failed at: Punishment{id=-1, name='DeikiYT', uuid='520217431f2f4a82815e749ef8e297fd', reason='Malicious Intent - Investigating Plugins, Commands Available & Bypassing Proxy. Contact us on Discord for more information: https://discord.gg/PraFvNv', operator='minecraftdan1234', start=1594549578424, end=-1, calculation='', type=BAN}

```

I am presuming I need to change my table encoding to the one specified above. It seems the reason I am giving is very long even though it is pretty normal length.

**Comment by DevLeoko** [comment]
@minecraftdan1234 the problem you reported is completely unrelated to the one in this thread.

Reasons are limited to 100 characters. Use message layouts for such "fixed" reason texts.

**Comment by NotStarRift** [comment]
> utf8mb4_general_ci

Wait, I'm confused. Because I changed Properties to characterEncoding=utf8mb4_general_ci' and I get this error log saying it's unsupported lol!

[20:06:36] Failed enabling database-manager...
[20:06:36] me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Unsupported character encoding 'utf8mb4_general_ci'.
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:595)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:581)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at me.leoko.advancedban.utils.DynamicDataSource.generateDataSource(DynamicDataSource.java:37)
	at me.leoko.advancedban.manager.DatabaseManager.setup(DatabaseManager.java:51)
	at me.leoko.advancedban.Universal.setup(Universal.java:63)
	at me.leoko.advancedban.bukkit.BukkitMain.onEnable(BukkitMain.java:23)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483)
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:366)
	at com.rylinaux.plugman.util.PluginUtil.load(PluginUtil.java:318)
	at com.rylinaux.plugman.util.PluginUtil.reload(PluginUtil.java:380)
	at com.rylinaux.plugman.command.ReloadCommand.execute(ReloadCommand.java:122)
	at com.rylinaux.plugman.PlugManCommandHandler.onCommand(PlugManCommandHandler.java:95)
	at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45)
	at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:159)
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchCommand(CraftServer.java:794)
	at org.bukkit.craftbukkit.v1_16_R1.CraftServer.dispatchServerCommand(CraftServer.java:756)
	at net.minecraft.server.v1_16_R1.DedicatedServer.handleCommandQueue(DedicatedServer.java:411)
	at net.minecraft.server.v1_16_R1.DedicatedServer.b(DedicatedServer.java:378)
	at net.minecraft.server.v1_16_R1.MinecraftServer.a(MinecraftServer.java:1212)
	at net.minecraft.server.v1_16_R1.MinecraftServer.v(MinecraftServer.java:1000)
	at net.minecraft.server.v1_16_R1.MinecraftServer.lambda$a$0(MinecraftServer.java:177)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Unsupported character encoding 'utf8mb4_general_ci'.
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:898)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:887)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:861)
	at com.mysql.jdbc.ConnectionPropertiesImpl.postInitialization(ConnectionPropertiesImpl.java:2575)
	at com.mysql.jdbc.ConnectionPropertiesImpl.initializeProperties(ConnectionPropertiesImpl.java:2545)
	at com.mysql.jdbc.ConnectionImpl.initializeDriverProperties(ConnectionImpl.java:3109)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:758)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:403)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	... 24 more

**Comment by DevLeoko** [comment]
This is the exact same error the user above had. If you read carefully you will find that he then did not change the properties but the encoding of the actual tables in the database to get it working.
