### ISSUE TITLE
MySQL Error

### ISSUE THREAD

**Issue by TeamBrave** [DevLeoko/AdvancedBan#384]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.2.1
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
PaperSpigot-1.8.8-R0.1

_Please provide the EXACT steps required to reproduce the problem..._
1. The error I got when entering the server "[AdvancedBan] Failed to load player data"
2.
3.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
https://pastebin.com/YgtvB4VS

_Add any additional information below._

**Comment by DevLeoko** [comment]
Is this the content of `/plugins/AdvancedBan/logs/latest.log`?
Check if there are any errors when the server starts

**Comment by Ymxer** [comment]
Query: 
SELECT * FROM `Punishments` WHERE `uuid` = ? OR `uuid` = ?
[07:51:56] java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30017ms.
 at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
 at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
 at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
 at me.leoko.advancedban.shaded.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
 at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:111)
 at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:107)
 at me.leoko.advancedban.manager.DatabaseManager.executeResultStatement(DatabaseManager.java:103)
 at me.leoko.advancedban.manager.PunishmentManager.load(PunishmentManager.java:63)
 at me.leoko.advancedban.Universal.callConnection(Universal.java:304)
 at me.leoko.advancedban.bukkit.listener.ConnectionListener.onConnect(ConnectionListener.java:23)
 at sun.reflect.GeneratedMethodAccessor249.invoke(Unknown Source)
 at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
 at java.lang.reflect.Method.invoke(Unknown Source)
 at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:300)
 at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:74)
 at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:62)
 at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:517)
 at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:499)
 at net.minecraft.server.v1_8_R3.LoginListener$LoginHandler.fireEvents(LoginListener.java:248)
 at net.minecraft.server.v1_8_R3.LoginListener$2.run(LoginListener.java:172)
 at java.lang.Thread.run(Unknown Source)

**Comment by Hopefuls** [comment]
There should be errors during thr start of your server then if your connection is is not available.
