### ISSUE TITLE
AdvancedBan don t create folder

### ISSUE THREAD

**Issue by TreeV2** [DevLeoko/AdvancedBan#395]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_ 2.2.1
 
 
_What kind of server do you have (`Bungeecord/single server`)?_ single server
 
 
_What server version (/version) are you using?_ 1.8

_Add any additional information below._ I  put plugin in plugin folder and start server in plugin folder AdvancedBan plugin don t creater folder  Error occurred while enabling AdvancedBan v2.2.1 (Is it up to date?)
java.lang.NoClassDefFoundError: com/google/gson/Gson
        at me.leoko.advancedban.Universal.<init>(Universal.java:39) ~[?:?]
        at me.leoko.advancedban.Universal.get(Universal.java:47) ~[?:?]
        at me.leoko.advancedban.bukkit.BukkitMain.onEnable(BukkitMain.java:23) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:335) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.loadPlugin(CraftServer.java:356) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.craftbukkit.v1_8_R1.CraftServer.enablePlugins(CraftServer.java:316) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.q(MinecraftServer.java:402) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.k(MinecraftServer.java:370) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.a(MinecraftServer.java:325) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.DedicatedServer.init(DedicatedServer.java:211) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at net.minecraft.server.v1_8_R1.MinecraftServer.run(MinecraftServer.java:505) [spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_261]
Caused by: java.lang.ClassNotFoundException: com.google.gson.Gson
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_261]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101) ~[spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86) ~[spigot-1.8.jar:git-Spigot-550ebace-7019900e]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_261]
        ... 14 more

**Comment by Hopefuls** [comment]
What other Plugins are you using on your server?

**Comment by TreeV2** [comment]
> What other Plugins are you using on your server?
worldguard-6.2
worldedit-bukkit-6.1.9
VoidGenerator
ViaVersion-3.1.0
Vault
TAB v2.8.3
SuperVanish
Spicord_2.6.0-SNAPSHOT
SimpleRestart
ServerRestorer
ProtocolLib
PowerNBT
PluginHider-1.6
PlaceholderAPI-2.10.9
PermissionsEx-1.23.4
NoRainReloaded
Negativity (1)
Multiverse-Portals-2.5
Multiverse-Core-2.5
LaggRemover-2.0.6
InvSee
FlameCord 
EssentialsXChat-2.0.1 
EssentialsX-2.0.1
Eggwars
Citizens
BWSBA
BWKits-2.0
BedwarsScoreBoardAddon-2.10.2-English
BedwarsRel-1.3.6
BanAnnouncer_2.0.1
AuthMe-5.4.0
AntiXRay-1.8.6
AntiCheatPlus
AntiBot
AdvancedAutoBan-1.0.2-SNAPSHOT

**Comment by DevLeoko** [comment]
Gson should be included in your server jar. Try to use a different Spigot.jar

**Comment by TreeV2** [comment]
from ?

**Comment by DevLeoko** [comment]
Build Tools or https://getbukkit.org/download/spigot

**Comment by TreeV2** [comment]
i have latest build tool

**Comment by DevLeoko** [comment]
Try to remove all other plugins or to use a different Spigot.jar

**Comment by TreeV2** [comment]
> Try to remove all other plugins or to use a different Spigot.jar

i try it and don t work

**Comment by A248** [comment]
> org.bukkit.craftbukkit.v1_8_R1

You're using mere 1.8 which doesn't have Gson. Use 1.8.8
