### ISSUE TITLE
problem with mysql

### ISSUE THREAD

**Issue by imreaches** [DevLeoko/AdvancedBan#404]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
2.2.1
 
 
_What kind of server do you have (`Bungeecord/single server`)?_
 bungeecord
 
_What server version (/version) are you using?_
spigot

_Please provide the EXACT steps required to reproduce the problem..._
1. create a mysql database
2. trying to connect more than one server to this
3. and get the error (java.sql.SQLException: Unknown system variable 'tx_isolation')

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
`[17:37:11] Failed enabling database-manager...
[17:37:11] me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Unknown system variable 'tx_isolation'
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:595)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:574)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at me.leoko.advancedban.utils.DynamicDataSource.generateDataSource(DynamicDataSource.java:37)
	at me.leoko.advancedban.manager.DatabaseManager.setup(DatabaseManager.java:51)
	at me.leoko.advancedban.Universal.setup(Universal.java:63)
	at me.leoko.advancedban.bukkit.BukkitMain.onEnable(BukkitMain.java:23)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:357)
	at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:317)
	at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:414)
	at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:378)
	at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:333)
	at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:263)
	at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:525)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.sql.SQLException: Unknown system variable 'tx_isolation'
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:1073)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3593)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3525)
	at com.mysql.jdbc.MysqlIO.sendCommand(MysqlIO.java:1986)
	at com.mysql.jdbc.MysqlIO.sqlQueryDirect(MysqlIO.java:2140)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2620)
	at com.mysql.jdbc.ConnectionImpl.execSQL(ConnectionImpl.java:2570)
	at com.mysql.jdbc.StatementImpl.executeQuery(StatementImpl.java:1474)
	at com.mysql.jdbc.ConnectionImpl.getTransactionIsolation(ConnectionImpl.java:3198)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.checkDefaultIsolation(PoolBase.java:479)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.checkDriverSupport(PoolBase.java:442)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.setupConnection(PoolBase.java:410)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:363)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	... 17 more
`

_Add any additional information below._
i did a search and found that using mysql 8 this variable was renamed to "transaction_isolation" so since i didn't find any references in the plugin folder, i was wondering if i should update it somewhere or in some file as well. Another problem I encountered (I don't know whether to open another one or not) comuqnue as written here on github I tried both to set the permissions in the bungeecord groups and before again since I use luckperms to add them there as suggested but I keep getting always the message of no-permissions. How could I resolve both issues?

**Comment by Hopefuls** [comment]
This is an issue that has always been present in AdvancedBan. Downgrading your mysql server version will both make advancedban compatible with AdvancedBan and presumably other plugins using an older hikari version.

**Comment by imreaches** [comment]
Ok thanks, I brought back a mysql version and it worked. What can i do about the permissions on bungeecord? I use luckperms

**Comment by DevLeoko** [comment]
Make sure to also install luckperms on bungeecord as AdvancedBan requires bungeecord permissions. Setting them in the bungee config should also work.

**Comment by imreaches** [comment]
The plugin is present on all bungeecord servers including, i tried both luckperms and bungeecord groups but neither option worked.

**Comment by imreaches** [comment]
thanks everyone, I solved. I close
