### ISSUE TITLE
advancedban Database connection error

### ISSUE THREAD

**Issue by huachizhu** [DevLeoko/AdvancedBan#420]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 AdvancedBan 2.2.1

_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord or WaterFall
 
_What server version (/version) are you using?_
New Bungeecord or WaterFall

_Please provide the EXACT steps required to reproduce the problem..._
1.MySQL error
2.Not connect MySQL
3.The old version is still the same
4.Mysql on-line.but the Plugins Display error

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
[11:09:48] Failed enabling database-manager...
[11:09:48] me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: Access denied for user 'root'@'localhost' (using password: YES)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:595)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:581)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at me.leoko.advancedban.utils.DynamicDataSource.generateDataSource(DynamicDataSource.java:37)
	at me.leoko.advancedban.manager.DatabaseManager.setup(DatabaseManager.java:51)
	at me.leoko.advancedban.Universal.setup(Universal.java:63)
	at me.leoko.advancedban.bungee.BungeeMain.onEnable(BungeeMain.java:23)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:300)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)
Caused by: java.sql.SQLException: Access denied for user 'root'@'localhost' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:965)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3933)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3869)
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:864)
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1707)
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1217)
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2189)
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2220)
	at com.mysql.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:2015)
	at com.mysql.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:768)
	at com.mysql.jdbc.JDBC4Connection.<init>(JDBC4Connection.java:47)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source)
	at java.lang.reflect.Constructor.newInstance(Unknown Source)
	at com.mysql.jdbc.Util.handleNewInstance(Util.java:425)
	at com.mysql.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:385)
	at com.mysql.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:323)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560)
	... 10 more

[11:09:48] An unexpected error has occurred connecting to the database
Check if your MySQL data is correct and if your MySQL-Server is online
Please check the plugins/AdvancedBan/logs/latest.log file and report this error in: https://github.com/DevLeoko/AdvancedBan/issues
[11:09:48] java.lang.NullPointerException
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:111)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:107)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:92)
	at me.leoko.advancedban.manager.PunishmentManager.setup(PunishmentManager.java:38)
	at me.leoko.advancedban.Universal.setup(Universal.java:70)
	at me.leoko.advancedban.bungee.BungeeMain.onEnable(BungeeMain.java:23)
	at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:300)
	at net.md_5.bungee.BungeeCord.start(BungeeCord.java:289)
	at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:62)
	at net.md_5.bungee.Bootstrap.main(Bootstrap.java:15)

_Add any additional information below._

**Comment by Hopefuls** [comment]
Hey hey,

Where are you entering the MySQL Credentials?
