### ISSUE TITLE
Console spam

### ISSUE THREAD

**Issue by Comstepr** [DevLeoko/AdvancedBan#425]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 [07:45:03 INFO]: -===== AdvancedBan v2 =====- 
[07:45:03 INFO]:   Dev • Leoko
[07:45:03 INFO]:   Status • Stable
[07:45:03 INFO]:   Version • 2.2.1
[07:45:03 INFO]:   License • Public
[07:45:03 INFO]:   Storage • HSQLDB (local)
[07:45:03 INFO]:   Server • Spigot/Bukkit
[07:45:03 INFO]:   UUID-Mode • INTERN
[07:45:03 INFO]:   Prefix • <redacted>
[07:45:03 INFO]: -==============
 
_What kind of server do you have (`Bungeecord/single server`)?_
 
 Using on Tuinity
_What server version (/version) are you using?_
`[07:44:51 INFO]: This server is running Tuinity version git-Tuinity-"5df4a4f" (MC: 1.16.3) (Implementing API version 1.16.3-R0.1-SNAPSHOT)
[07:44:51 INFO]: Checking version, please wait...
[07:44:52 INFO]: Previous version: git-Tuinity-"de1983b" (MC: 1.16.3)
[07:44:52 INFO]: You are running the latest version
`

_Please provide the EXACT steps required to reproduce the problem..._
Ban someone

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
```[07:44:01 WARN]: [AdvancedBan] Task #4507788 for AdvancedBan v2.2.1 generated an exception
java.lang.IllegalStateException: RevokePunishmentEvent may only be triggered asynchronously.
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:593) ~[patched_1.16.3.jar:git-Tuinity-"5df4a4f"]
        at me.leoko.advancedban.bukkit.BukkitMethods.lambda$callRevokePunishmentEvent$6(BukkitMethods.java:378) ~[?:?]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftTask.run(CraftTask.java:99) ~[patched_1.16.3.jar:git-Tuinity-"5df4a4f"]
        at org.bukkit.craftbukkit.v1_16_R2.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:468) ~[patched_1.16.3.jar:git-Tuinity-"5df4a4f"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.b(MinecraftServer.java:1354) ~[patched_1.16.3.jar:git-Tuinity-"5df4a4f"]
        at net.minecraft.server.v1_16_R2.DedicatedServer.b(DedicatedServer.java:372) ~[patched_1.16.3.jar:git-Tuinity-"5df4a4f"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.a(MinecraftServer.java:1267) ~[patched_1.16.3.jar:git-Tuinity-"5df4a4f"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.w(MinecraftServer.java:999) ~[patched_1.16.3.jar:git-Tuinity-"5df4a4f"]
        at net.minecraft.server.v1_16_R2.MinecraftServer.lambda$a$0(MinecraftServer.java:177) ~[patched_1.16.3.jar:git-Tuinity-"5df4a4f"]
        at java.lang.Thread.run(Thread.java:834) [?:?]```

_Add any additional information below._

**Comment by Hopefuls** [comment]
Update to 2.3.0 and try again

**Comment by Comstepr** [comment]
Seems resolved
