### ISSUE TITLE
ConcurrentModificationException on tempban command executed by another plugin

### ISSUE THREAD

**Issue by AerWyn81** [DevLeoko/AdvancedBan#462]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 AdvancedBan 2.3.0
 
_What kind of server do you have (`Bungeecord/single server`)?_
Simple Vanilla server
 
_What server version (/version) are you using?_
git-Paper-467 (MC: 1.16.5)

_Please provide the EXACT steps required to reproduce the problem..._
Unfortunately I don't know. We use a time-based reward plugin [(LitePlaytimeRewards)](https://www.spigotmc.org/resources/1-12-1-16-liteplaytimerewards-give-customizable-playtime-rewards-with-ease.71784/) that will execute a temp ban command. This "Warn" only appeared once today and the player was not temp-ban.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
Log : https://pastebin.com/Phn8YMs7
AdvancedBan log : https://pastebin.com/wijkj6vk
AdvancedBan yesterday log (not related but.. weird?) : https://pastebin.com/pqxYANyx

Thanks :)

**Comment by stonegray** [comment]
I'm having a related issue on BungeeCord install at the same place (`me.leoko.advancedban.manager.PunishmentManager.getPunishments(PunishmentManager.java:133)`)

- AdvancedBans 2.3.0
- Waterfall build 398

Full error attached below:

<details>
<summary> Full error text (click to expand) </summary>

```
[20:35:16 WARN]: Error dispatching event LoginEvent(cancelled=false, cancelReasonComponents=null, loginResult=LoginResult(id=dea210dee40046e2b21b8337e836ca75, name=detroittiger123, properties=[LoginResult.Property(name=textures, value=ewogICJ0aW1lc3RhbXAiIDogMTYxNDM2ODExNjU3NiwKICAicHJvZmlsZUlkIiA6ICJkZWEyMTBkZWU0MDA0NmUyYjIxYjgzMzdlODM2Y2E3NSIsCiAgInByb2ZpbGVOYW1lIiA6ICJkZXRyb2l0dGlnZXIxMjMiLAogICJzaWduYXR1cmVSZXF1aXJlZCIgOiB0cnVlLAogICJ0ZXh0dXJlcyIgOiB7CiAgICAiU0tJTiIgOiB7CiAgICAgICJ1cmwiIDogImh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOGM2OTY1Mjk2YjQzYjAzMjRiOThlOTViNGNlZDllMGM2NWRhOTczY2I4YWIxZDk5YjQ3MGEwMGM2NmJiZDZlMSIKICAgIH0KICB9Cn0=, signature=xiSVF8Vos5UpqiFgMjGjp1YvV6NaIwncO2H7Wieae5yEN17I6Hy4aiYA5albimIracMLjobo/Yae4YP6T1dpeJWv/JewNBKKfwwNEq9467Jp6swQ4/bjfm/OXfRfIc3ZH6qD50ZiN+/GLWYZFbgVbS7eDDUm/M4AqmxJRizmgRohfSlBPJQwLdpvrYwrNjlP1cOvE1UaQ9YdOD13qUAGfiRPD7vy+OFTjdwZkS31UbjgFAttLuUSz3Vei08TRrsQ2ithtlf6Hnchp4won7e2hZvHtPB9h2tBwXOgrKOkjcqygFYCdPVhTGmPSLaKHmrKZtOsRyyh2i7flIT3bPiq5pDkD/c8xUy1ljPkyKFZRiJu3Du0K5aCWCgtdR0CocfSV6w0AGb5kGRPqeh6azgUtMWOiArIVu5Gh92TfJIE4iAXNdXfvFOJhHVSpQh0W/JOyRF5IsREXLI0lo0Jz9erZxd/i1sL6DTIrT9JuQCTvVO7nSY77tp2sIbD3126K1O6iBqj8pAF41By5ynoK9mO3ntpDrbthH5ypl7GDYQYZKiBrMxVepuDYzri0DZrM0loBequV2Ha7KApx+AbhaYNoKhm9kBz1PJD082pDspNGQzceUe/7QhsGjUue1LWJj3Uo8RNXMjVOFpRp40Kdx0+T6eNO7vsRpR6e0Yxh0d/uyo=)]), connection=[[ [redacted] ] <-> InitialHandler) to listener com.james090500.Bungee.Listeners.BanListnerBungee@526e8108
java.util.ConcurrentModificationException: null
        at java.util.HashMap$HashIterator.remove(HashMap.java:1507) ~[?:?]
        at me.leoko.advancedban.manager.PunishmentManager.getPunishments(PunishmentManager.java:133) ~[?:?]
        at me.leoko.advancedban.manager.PunishmentManager.getBan(PunishmentManager.java:266) ~[?:?]
        at me.leoko.advancedban.manager.PunishmentManager.isBanned(PunishmentManager.java:288) ~[?:?]
        at com.james090500.Bungee.Listeners.BanListnerBungee.onConnect(BanListnerBungee.java:89) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:566) ~[?:?]
        at net.md_5.bungee.event.EventHandlerMethod.invoke(EventHandlerMethod.java:19) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at net.md_5.bungee.event.EventBus.post(EventBus.java:47) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at net.md_5.bungee.api.plugin.PluginManager.callEvent(PluginManager.java:453) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at net.md_5.bungee.connection.InitialHandler.finish(InitialHandler.java:579) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at net.md_5.bungee.connection.InitialHandler.access$700(InitialHandler.java:72) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at net.md_5.bungee.connection.InitialHandler$5.done(InitialHandler.java:472) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at net.md_5.bungee.connection.InitialHandler$5.done(InitialHandler.java:460) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at net.md_5.bungee.http.HttpHandler.done(HttpHandler.java:68) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at net.md_5.bungee.http.HttpHandler.channelRead0(HttpHandler.java:59) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at net.md_5.bungee.http.HttpHandler.channelRead0(HttpHandler.java:14) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:436) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:324) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:296) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:251) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1533) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1282) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1329) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:508) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:447) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.handler.timeout.IdleStateHandler.channelRead(IdleStateHandler.java:286) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.epoll.AbstractEpollStreamChannel$EpollStreamUnsafe.epollInReady(AbstractEpollStreamChannel.java:795) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.epoll.EpollEventLoop.processReady(EpollEventLoop.java:480) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.channel.epoll.EpollEventLoop.run(EpollEventLoop.java:378) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[waterfall.jar:git:Waterfall-Bootstrap:1.16-R0.5-SNAPSHOT:2b1ac19:398]
        at java.lang.Thread.run(Thread.java:834) [?:?]
```
</details>
