### ISSUE TITLE
Error database 

### ISSUE THREAD

**Issue by CloneXmmT** [DevLeoko/AdvancedBan#524]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.3.0
 
_What kind of server do you have (`Bungeecord/single server`)?_
 Bungeecord
 
_What server version (/version) are you using?_
1.17.1

_Please provide the EXACT steps required to reproduce the problem..._
1. I use command /tempban
2. Nothing will happen
3. An error appears in the console

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
https://pastebin.com/rGsxLWY4

_Add any additional information below._

Console

[17:46:17 INFO]: [AdvancedBan] An unexpected error has occurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report this error in: https://github.com/DevLeoko/AdvancedBan/issues
[17:46:17 INFO]: [AdvancedBan] Debug: Query:
INSERT INTO `Punishments` (`name`, `uuid`, `reason`, `operator`, `punishmentType`, `start`, `end`, `calculation`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
[17:46:17 INFO]: [AdvancedBan] Debug: An error has occurred with the database, the error code is: '1366'
[17:46:17 INFO]: [AdvancedBan] Debug: The state of the sql is: 22001
[17:46:17 INFO]: [AdvancedBan] Debug: Error message: Data truncation: Incorrect string value: '\xC5\xAF / u...' for column `bans`.`Punishments`.`reason` at row 1
[17:46:17 INFO]: [AdvancedBan] Debug: com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Incorrect string value: '\xC5\xAF / u...' for column `bans`.`Punishments`.`reason` at row 1
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
        at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
        at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:370)
        at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
        at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
        at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:122)
        at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:107)
        at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:92)
        at me.leoko.advancedban.utils.Punishment.create(Punishment.java:85)
        at me.leoko.advancedban.utils.Punishment.create(Punishment.java:46)
        at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:73)
        at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:19)
        at me.leoko.advancedban.utils.Command.execute(Command.java:552)
        at me.leoko.advancedban.manager.CommandManager.lambda$onCommand$0(CommandManager.java:46)
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftTask.run(CraftTask.java:101)
        at org.bukkit.craftbukkit.v1_17_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:57)
        at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
        at java.base/java.lang.Thread.run(Thread.java:831)

[17:46:18 INFO]: [AdvancedBan] !! Not able to update ID of punishment! Please restart the server to resolve this issue!
[17:46:18 INFO]: [AdvancedBan] !! Failed at: Punishment(name=jakub09, uuid=jakub09, operator=CONSOLE, calculation=, start=1628955977993, end=1630165577992, type=TEMP_BAN, reason=Tabovaní commandů / umyslné kopírovaní serveru, id=-1)

**Comment by tobgen** [comment]
Most likely related to collation settings in the DB, or other language-settings.
You are trying to insert a char that is "unknown" or the ban-reason may be too long.
Afaik there is a VARCHAR(100) somewhere that might cause this.

But, best guess, some collation setting. 

// T
