### ISSUE TITLE
Error while simple ban, Log provided

### ISSUE THREAD

**Issue by TechRoot** [DevLeoko/AdvancedBan#561]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.3.0
 
_What kind of server do you have (`Bungeecord/single server`)?_
 
 BungeeCord, WaterFall
 
_What server version (/version) are you using?_

1.18  Build 483
_Please provide the EXACT steps required to reproduce the problem..._
1. /ban PlayerName

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_
[17:11:16 INFO]: [AdvancedBan] An unexpected error has occurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report this error in: https://github.com/DevLeoko/AdvancedBan/issues

_Add any additional information below._

[17:10:01] An unexpected error has occurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report this error in: https://github.com/DevLeoko/AdvancedBan/issues
[17:10:01] Query: 
INSERT INTO `PunishmentHistory` (`name`, `uuid`, `reason`, `operator`, `punishmentType`, `start`, `end`, `calculation`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
[17:10:01] com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'reason' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:371)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:122)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:107)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:92)
	at me.leoko.advancedban.utils.Punishment.create(Punishment.java:81)
	at me.leoko.advancedban.utils.Punishment.create(Punishment.java:46)
	at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:73)
	at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:19)
	at me.leoko.advancedban.utils.Command.execute(Command.java:552)
	at me.leoko.advancedban.manager.CommandManager.lambda$onCommand$0(CommandManager.java:46)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[17:10:01] An unexpected error has occurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report this error in: https://github.com/DevLeoko/AdvancedBan/issues
[17:10:01] Query: 
INSERT INTO `Punishments` (`name`, `uuid`, `reason`, `operator`, `punishmentType`, `start`, `end`, `calculation`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
[17:10:01] com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'reason' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:371)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:122)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:107)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:92)
	at me.leoko.advancedban.utils.Punishment.create(Punishment.java:85)
	at me.leoko.advancedban.utils.Punishment.create(Punishment.java:46)
	at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:73)
	at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:19)
	at me.leoko.advancedban.utils.Command.execute(Command.java:552)
	at me.leoko.advancedban.manager.CommandManager.lambda$onCommand$0(CommandManager.java:46)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[17:10:01] !! Not able to update ID of punishment! Please restart the server to resolve this issue!
[17:10:01] !! Failed at: Punishment(name=Comandos, uuid=comandos, operator=techroot, calculation=, start=1650129001259, end=-1, type=BAN, reason=Aquí no aceptamos toxicidad.
En caso de que pretendas volver
Deberás pedir tu desbaneo mediante un ticket en el Discord
 http://techroot.tv/discord, id=-1)
[17:11:16] An unexpected error has occurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report this error in: https://github.com/DevLeoko/AdvancedBan/issues
[17:11:16] Query: 
INSERT INTO `PunishmentHistory` (`name`, `uuid`, `reason`, `operator`, `punishmentType`, `start`, `end`, `calculation`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
[17:11:16] com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'reason' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:371)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:122)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:107)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:92)
	at me.leoko.advancedban.utils.Punishment.create(Punishment.java:81)
	at me.leoko.advancedban.utils.Punishment.create(Punishment.java:46)
	at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:73)
	at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:19)
	at me.leoko.advancedban.utils.Command.execute(Command.java:552)
	at me.leoko.advancedban.manager.CommandManager.lambda$onCommand$0(CommandManager.java:46)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[17:11:16] An unexpected error has occurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report this error in: https://github.com/DevLeoko/AdvancedBan/issues
[17:11:16] Query: 
INSERT INTO `Punishments` (`name`, `uuid`, `reason`, `operator`, `punishmentType`, `start`, `end`, `calculation`) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
[17:11:16] com.mysql.cj.jdbc.exceptions.MysqlDataTruncation: Data truncation: Data too long for column 'reason' at row 1
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:104)
	at com.mysql.cj.jdbc.ClientPreparedStatement.executeInternal(ClientPreparedStatement.java:953)
	at com.mysql.cj.jdbc.ClientPreparedStatement.execute(ClientPreparedStatement.java:371)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.ProxyPreparedStatement.execute(ProxyPreparedStatement.java:44)
	at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariProxyPreparedStatement.execute(HikariProxyPreparedStatement.java)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:122)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:107)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:92)
	at me.leoko.advancedban.utils.Punishment.create(Punishment.java:85)
	at me.leoko.advancedban.utils.Punishment.create(Punishment.java:46)
	at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:73)
	at me.leoko.advancedban.utils.commands.PunishmentProcessor.accept(PunishmentProcessor.java:19)
	at me.leoko.advancedban.utils.Command.execute(Command.java:552)
	at me.leoko.advancedban.manager.CommandManager.lambda$onCommand$0(CommandManager.java:46)
	at net.md_5.bungee.scheduler.BungeeTask.run(BungeeTask.java:66)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)

[17:11:16] !! Not able to update ID of punishment! Please restart the server to resolve this issue!
[17:11:16] !! Failed at: Punishment(name=Comandos, uuid=comandos, operator=techroot, calculation=, start=1650129076217, end=-1, type=BAN, reason=Aquí no aceptamos toxicidad.
En caso de que pretendas volver
Deberás pedir tu desbaneo mediante un ticket en el Discord
 http://techroot.tv/discord, id=-1)

**Comment by Hopefuls** [comment]
Your reason string is too long. Consider using layouts instead.

**Comment by TechRoot** [comment]
Thank you.
