### ISSUE TITLE
Console spam with error (/mute command)

### ISSUE THREAD

**Issue by Evalutik** [DevLeoko/AdvancedBan#609]
When I write /mute, enter the player's nickname and press TAB, the plugin will give an error and spam the console (didn't check other commands)

_What version of AdvancedBan (`/AdvancedBan`) are you using?_ 2.3.0
 
 
_What kind of server do you have (`Bungeecord/single server`)?_ single server
 
 
_What server version (/version) are you using?_ PurPur 1.19.3

_Please provide the EXACT steps required to reproduce the problem..._
1. type /mute 
2. push TAB
3. push TAB

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)_

latest.log server file: https://pastebin.com/yvEQT1XT
latest.log plugin file: 
[20:14:27] Evalut is deleting a punishment
[20:14:27] Deleted punishment 28 from Evalutik punishment reason: &cnone 
(that's it)

Error in console: 

[20:15:49 ERROR]: Exception when Evalut attempted to tab complete mute Evalut 
org.bukkit.command.CommandException: Unhandled exception during tab completion for command '/mute Evalut ' in plugin AdvancedBan v2.3.0
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:150) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.Command.tabComplete(Command.java:93) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.command.SimpleCommandMap.tabComplete(SimpleCommandMap.java:253) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.tabCompleteCommand(CraftServer.java:2379) ~[purpur-1.19.3.jar:git-Purpur-1912]
	at org.bukkit.craftbukkit.v1_19_R2.CraftServer.tabComplete(CraftServer.java:2351) ~[purpur-1.19.3.jar:git-Purpur-1912]
	at org.bukkit.craftbukkit.v1_19_R2.command.BukkitCommandWrapper.getSuggestions(BukkitCommandWrapper.java:74) ~[purpur-1.19.3.jar:git-Purpur-1912]
	at com.mojang.brigadier.tree.ArgumentCommandNode.listSuggestions(ArgumentCommandNode.java:71) ~[brigadier-1.0.18.jar:git-Purpur-1912]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:601) ~[purpur-1.19.3.jar:?]
	at com.mojang.brigadier.CommandDispatcher.getCompletionSuggestions(CommandDispatcher.java:581) ~[purpur-1.19.3.jar:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleCustomCommandSuggestions$5(ServerGamePacketListenerImpl.java:939) ~[?:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.19.3.jar:git-Purpur-1912]
	at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
	at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1368) ~[purpur-1.19.3.jar:git-Purpur-1912]
	at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.19.3.jar:git-Purpur-1912]
	at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
	at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1345) ~[purpur-1.19.3.jar:git-Purpur-1912]
	at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1338) ~[purpur-1.19.3.jar:git-Purpur-1912]
	at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
	at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1316) ~[purpur-1.19.3.jar:git-Purpur-1912]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1204) ~[purpur-1.19.3.jar:git-Purpur-1912]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[purpur-1.19.3.jar:git-Purpur-1912]
	at java.lang.Thread.run(Thread.java:1589) ~[?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "org.bukkit.configuration.ConfigurationSection.getKeys(boolean)" because the return value of "org.bukkit.configuration.file.YamlConfiguration.getConfigurationSection(String)" is null
	at me.leoko.advancedban.bukkit.BukkitMethods.getKeys(BukkitMethods.java:115) ~[AdvancedBan-Bundle-2.3.0-RELEASE.jar:?]
	at me.leoko.advancedban.utils.tabcompletion.PunishmentTabCompleter.onTabComplete(PunishmentTabCompleter.java:54) ~[AdvancedBan-Bundle-2.3.0-RELEASE.jar:?]
	at me.leoko.advancedban.bukkit.BukkitMethods.lambda$setCommandExecutor$2(BukkitMethods.java:169) ~[AdvancedBan-Bundle-2.3.0-RELEASE.jar:?]
	at org.bukkit.command.PluginCommand.tabComplete(PluginCommand.java:138) ~[purpur-api-1.19.3-R0.1-SNAPSHOT.jar:?]
	... 22 more

_Add any additional information below._

![image](https://user-images.githubusercontent.com/126126362/228646533-e95eff08-b967-49cb-b071-3cb890151131.png)

![image](https://user-images.githubusercontent.com/126126362/228646588-891a92ce-e13e-4e02-95a4-6a835d58a62c.png)

**Comment by Evalutik** [comment]
![image](https://user-images.githubusercontent.com/126126362/228646872-2abde765-8434-4061-9fab-38958656b8ca.png)
all my plugins

**Comment by Hopefuls** [comment]
a configuration file seems to be malformed within your advancedban installation. The error does not mention what issue, so I might suggest resetting your configuration while keeping a backup of it to see if thats the issue or not.
