### ISSUE TITLE
MySQL error

### ISSUE THREAD

**Issue by CubicLemming749** [DevLeoko/AdvancedBan#618]
_What version of AdvancedBan (`/AdvancedBan`) are you using?
2.30-RELEASE
 
 
_What kind of server do you have (`Bungeecord/single server`)?
BungeeCord
 
 
_What server version (/version) are you using?_
NullCordX 3.7.4

_Please provide the EXACT steps required to reproduce the problem..._
1. Start the server
2. Try to join
3. Now you have the error.

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include /plugins/AdvancedBan/logs/latest.log)

https://pastebin.com/dr3STRKD

_Add any additional information below._

Other plugin databases were failing, but now only AdvancedBan is failing.

**Comment by Hopefuls** [comment]
Please provide error messages from the start of your server, the error
indicates that the MySQL connection is closed.

**Comment by CubicLemming749** [comment]
[23:44:48 INFO]: [AdvancedBan] Offline permission support through LuckPerms active
[23:44:48 ERROR]: Loading class `com.mysql.jdbc.Driver'. This is deprecated. The new driver class is `com.mysql.cj.jdbc.Driver'. The driver is automatically registered via the SPI and manual loading of the driver class is generally unnecessary.
[23:44:48 INFO] [me.leoko.advancedban.shaded.com.zaxxer.hikari.HikariDataSource]: HikariPool-1 - Starting...
[23:44:52 INFO] [NullCordX]: HandCaptcha generated in 17,563 ms
[23:44:52 INFO] [NullCordX]: Found 1000 dirty FramedCaptcha to regenerate!
[23:44:52 INFO] [NullCordX]: Async FramedCaptcha generation will continue in parallel with NullCordX loading.
[23:45:19 ERROR] [me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool]: HikariPool-1 - Exception during pool initialization.
com.mysql.cj.jdbc.exceptions.CommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at com.mysql.cj.jdbc.exceptions.SQLError.createCommunicationsException(SQLError.java:174) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:64) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:824) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:237) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:198) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        at me.leoko.advancedban.shaded.com.zaxxer.hikari.util.DriverDataSource.getConnection(DriverDataSource.java:138) ~[?:?]
        at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.newConnection(PoolBase.java:358) ~[?:?]
        at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.newPoolEntry(PoolBase.java:206) ~[?:?]
        at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.createPoolEntry(HikariPool.java:477) ~[?:?]
        at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:560) ~[?:?]
        at me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115) ~[?:?]
        at me.leoko.advancedban.shaded.com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81) ~[?:?]
        at me.leoko.advancedban.utils.DynamicDataSource.generateDataSource(DynamicDataSource.java:37) ~[?:?]
        at me.leoko.advancedban.manager.DatabaseManager.setup(DatabaseManager.java:51) ~[?:?]
        at me.leoko.advancedban.Universal.setup(Universal.java:72) ~[?:?]
        at me.leoko.advancedban.bungee.BungeeMain.onEnable(BungeeMain.java:32) ~[?:?]
        at net.md_5.bungee.api.plugin.PluginManager.enablePlugins(PluginManager.java:281) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        at net.md_5.bungee.BungeeCord.start(BungeeCord.java:256) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        at net.md_5.bungee.BungeeCordLauncher.main(BungeeCordLauncher.java:57) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        at net.md_5.bungee.Bootstrap.main(Bootstrap.java:12) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
Caused by: com.mysql.cj.exceptions.CJCommunicationsException: Communications link failure
The last packet sent successfully to the server was 0 milliseconds ago. The driver has not received any packets from the server.
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:77) ~[?:?]
        at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45) ~[?:?]
        at java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499) ~[?:?]
        at java.lang.reflect.Constructor.newInstance(Constructor.java:480) ~[?:?]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:61) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:151) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        at com.mysql.cj.exceptions.ExceptionFactory.createCommunicationsException(ExceptionFactory.java:167) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:89) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        at com.mysql.cj.NativeSession.connect(NativeSession.java:120) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:944) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:814) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        ... 18 more
Caused by: java.net.SocketTimeoutException: Connect timed out
        at sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) ~[?:?]
        at sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[?:?]
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[?:?]
        at java.net.Socket.connect(Socket.java:633) ~[?:?]
        at com.mysql.cj.protocol.StandardSocketFactory.connect(StandardSocketFactory.java:153) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        at com.mysql.cj.protocol.a.NativeSocketConnection.connect(NativeSocketConnection.java:63) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        at com.mysql.cj.NativeSession.connect(NativeSession.java:120) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        at com.mysql.cj.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:944) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:814) ~[nullcordx.jar:1.19-R0.1-SNAPSHOT]
        ... 18 more
[23:45:19 INFO]: [AdvancedBan] Failed enabling database-manager...
[23:45:19 INFO]: [AdvancedBan] An unexpected error has occurred connecting to the database
Check if your MySQL data is correct and if your MySQL-Server is online
Please check the plugins/AdvancedBan/logs/latest.log file and report this error in: https://github.com/DevLeoko/AdvancedBan/issues

**Comment by Hopefuls** [comment]
Your database is not reachable, ensure that it is.
