### ISSUE TITLE
HikariPool Error

### ISSUE THREAD

**Issue by LuoyeAutumn** [DevLeoko/AdvancedBan#630]
_What version of AdvancedBan (`/AdvancedBan`) are you using?_
 2.30 Public
 
_What kind of server do you have (`Bungeecord/single server`)?_
single server，but I‘m a Bungeecord Server
 
_What server version (/version) are you using?_
1.20.1

_Please provide the EXACT steps required to reproduce the problem..._
1.join the server
2.An error has occurred
3.the server console prompts ：

[13:31:32 WARN]: [me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@194141c6 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[13:31:37 WARN]: [me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@587c4bfd (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[13:31:39 INFO]: Villager EntityVillager['Villager'/21222, uuid='2dbbd608-bda0-4750-a669-d8b078cd6331', l='ServerLevel[world]', x=7908.66, y=39.00, z=-1535.69, cpos=[494, -96], tl=2130987, v=true] died, message: 'Villager was slain by MINECRAFT_Wendy'
[13:31:42 WARN]: [me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@7a32b139 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[13:31:47 WARN]: [me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@24a34a5 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[13:31:52 WARN]: [me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@578771f8 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[13:31:57 WARN]: [me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@4af2c310 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[13:31:57 INFO]: [AdvancedBan] An unexpected error has occurred executing an Statement in the database
[13:31:57 INFO]: Please check the plugins/AdvancedBan/logs/latest.log file and report this error in: https://github.com/DevLeoko/AdvancedBan/issues
[13:31:57 INFO]: com.mojang.authlib.GameProfile@52de3d2b[id=9b781622-71c8-3adf-b758-9a518a41b270,name=Luoye_Autumn,properties={textures=[com.mojang.authlib.properties.Property@1786bd46]},legacy=false] (/39.158.162.94:60653) lost connection: Disconnected
[13:32:02 WARN]: [me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@c4ff5de (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[13:32:07 WARN]: [me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@37aa0f55 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[13:32:12 WARN]: [me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@5e6ff310 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[13:32:17 WARN]: [me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase] HikariPool-1 - Failed to validate connection com.mysql.cj.jdbc.ConnectionImpl@d3b0300 (No operations allowed after connection closed.). Possibly consider using a shorter maxLifetime value.
[13:32:17 INFO]: Disconnecting com.mojang.authlib.GameProfile@ef13545[id=9b781622-71c8-3adf-b758-9a518a41b270,name=Luoye_Autumn,properties={textures=[com.mojang.authlib.properties.Property@2f27a4c2]},legacy=false] (/112.158.67.2:60653): [AdvancedBan] Failed to load player data!

4.After a while, Client prompts：Exception Connecting:ReadTimeoutException : null

_Any error/log post it through [pastebin.com](http://pastebin.com) and link it here. (Also include [[[/plugins/AdvancedBan/logs/latest.log)_

[13:15:27] An unexpected error has occurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report this error in: https://github.com/DevLeoko/AdvancedBan/issues
[13:15:27] Query: 
SELECT * FROM `Punishments` WHERE `uuid` = ? OR `uuid` = ?
[13:15:27] java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30004ms.
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:111)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:107)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.manager.DatabaseManager.executeResultStatement(DatabaseManager.java:103)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.manager.PunishmentManager.load(PunishmentManager.java:63)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.Universal.callConnection(Universal.java:304)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.bukkit.listener.ConnectionListener.onConnect(ConnectionListener.java:23)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor149.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
	at net.minecraft.server.network.LoginListener$LoginHandler.fireEvents(LoginListener.java:395)
	at net.minecraft.server.network.LoginListener$1.run(LoginListener.java:280)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:111)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:74)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2457)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:560)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:173)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
	... 20 more
Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
	at jdk.internal.reflect.GeneratedConstructorAccessor128.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)
	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:753)
	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:565)
	at com.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2453)
	... 23 more

[13:25:59] An unexpected error has occurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report this error in: https://github.com/DevLeoko/AdvancedBan/issues
[13:25:59] Query: 
SELECT * FROM `Punishments` WHERE `uuid` = ? OR `uuid` = ?
[13:25:59] java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30004ms.
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:111)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:107)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.manager.DatabaseManager.executeResultStatement(DatabaseManager.java:103)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.manager.PunishmentManager.load(PunishmentManager.java:63)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.Universal.callConnection(Universal.java:304)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.bukkit.listener.ConnectionListener.onConnect(ConnectionListener.java:23)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor149.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
	at net.minecraft.server.network.LoginListener$LoginHandler.fireEvents(LoginListener.java:395)
	at net.minecraft.server.network.LoginListener$1.run(LoginListener.java:280)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:111)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:74)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2457)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:560)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:173)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
	... 20 more
Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
	at jdk.internal.reflect.GeneratedConstructorAccessor128.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)
	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:753)
	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:565)
	at com.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2453)
	... 23 more

[13:31:57] An unexpected error has occurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report this error in: https://github.com/DevLeoko/AdvancedBan/issues
[13:31:57] Query: 
SELECT * FROM `Punishments` WHERE `uuid` = ? OR `uuid` = ?
[13:31:57] java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30002ms.
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:111)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:107)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.manager.DatabaseManager.executeResultStatement(DatabaseManager.java:103)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.manager.PunishmentManager.load(PunishmentManager.java:63)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.Universal.callConnection(Universal.java:304)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.bukkit.listener.ConnectionListener.onConnect(ConnectionListener.java:23)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor149.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
	at net.minecraft.server.network.LoginListener$LoginHandler.fireEvents(LoginListener.java:395)
	at net.minecraft.server.network.LoginListener$1.run(LoginListener.java:280)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:111)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:74)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2457)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:560)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:173)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
	... 20 more
Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
	at jdk.internal.reflect.GeneratedConstructorAccessor128.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)
	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:753)
	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:565)
	at com.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2453)
	... 23 more

[13:58:35] An unexpected error has occurred executing an Statement in the database
Please check the plugins/AdvancedBan/logs/latest.log file and report this error in: https://github.com/DevLeoko/AdvancedBan/issues
[13:58:35] Query: 
SELECT * FROM `Punishments` WHERE `uuid` = ? OR `uuid` = ?
[13:58:35] java.sql.SQLTransientConnectionException: HikariPool-1 - Connection is not available, request timed out after 30004ms.
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.createTimeoutException(HikariPool.java:695)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:197)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:162)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.HikariDataSource.getConnection(HikariDataSource.java:100)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:111)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:107)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.manager.DatabaseManager.executeResultStatement(DatabaseManager.java:103)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.manager.PunishmentManager.load(PunishmentManager.java:63)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.Universal.callConnection(Universal.java:304)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.bukkit.listener.ConnectionListener.onConnect(ConnectionListener.java:23)
	at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor149.execute(Unknown Source)
	at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77)
	at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:77)
	at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70)
	at io.papermc.paper.plugin.manager.PaperEventManager.callEvent(PaperEventManager.java:54)
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.callEvent(PaperPluginManagerImpl.java:126)
	at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:617)
	at net.minecraft.server.network.LoginListener$LoginHandler.fireEvents(LoginListener.java:395)
	at net.minecraft.server.network.LoginListener$1.run(LoginListener.java:280)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.sql.SQLNonTransientConnectionException: No operations allowed after connection closed.
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:111)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:98)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:90)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:64)
	at com.mysql.cj.jdbc.exceptions.SQLError.createSQLException(SQLError.java:74)
	at com.mysql.cj.jdbc.exceptions.SQLExceptionsMapping.translateException(SQLExceptionsMapping.java:73)
	at com.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2457)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.setNetworkTimeout(PoolBase.java:560)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.PoolBase.isConnectionAlive(PoolBase.java:173)
	at AdvancedBan-Bundle-2.3.0-RELEASE.jar//me.leoko.advancedban.shaded.com.zaxxer.hikari.pool.HikariPool.getConnection(HikariPool.java:186)
	... 20 more
Caused by: com.mysql.cj.exceptions.ConnectionIsClosedException: No operations allowed after connection closed.
	at jdk.internal.reflect.GeneratedConstructorAccessor128.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:62)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:105)
	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:150)
	at com.mysql.cj.NativeSession.checkClosed(NativeSession.java:753)
	at com.mysql.cj.jdbc.ConnectionImpl.checkClosed(ConnectionImpl.java:565)
	at com.mysql.cj.jdbc.ConnectionImpl.setNetworkTimeout(ConnectionImpl.java:2453)
	... 23 more

_Add any additional information below._

**Comment by neco222** [comment]
I am having trouble with the same error.
The same error seems to occur when connecting from a rental server.
Building the server within the same router will fix it.

**Comment by Hopefuls** [comment]
Connection issue when connecting to your database.

Not an issue with AdvancedBan
