### ISSUE TITLE
Mysql not work

### ISSUE THREAD

**Issue by ibrahim12651** [DevLeoko/AdvancedBan#635]
```
[21:09:01] An unexpected error has occurred connecting to the database
Check if your MySQL data is correct and if your MySQL-Server is online
Please check the plugins/AdvancedBan/logs/latest.log file and report this error in: https://github.com/DevLeoko/AdvancedBan/issues
[21:09:01] java.lang.NullPointerException: Cannot invoke "me.leoko.advancedban.shaded.com.zaxxer.hikari.HikariDataSource.getConnection()" because "this.dataSource" is null
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:111)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:107)
	at me.leoko.advancedban.manager.DatabaseManager.executeStatement(DatabaseManager.java:92)
	at me.leoko.advancedban.manager.PunishmentManager.setup(PunishmentManager.java:41)
	at me.leoko.advancedban.Universal.setup(Universal.java:79)
	at me.leoko.advancedban.bukkit.BukkitMain.onEnable(BukkitMain.java:22)
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263)
	at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342)
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugin(CraftServer.java:492)
	at org.bukkit.craftbukkit.v1_16_R3.CraftServer.enablePlugins(CraftServer.java:406)
	at net.minecraft.server.v1_16_R3.MinecraftServer.loadWorld(MinecraftServer.java:554)
	at net.minecraft.server.v1_16_R3.DedicatedServer.init(DedicatedServer.java:257)
	at net.minecraft.server.v1_16_R3.MinecraftServer.w(MinecraftServer.java:928)
	at net.minecraft.server.v1_16_R3.MinecraftServer.lambda$0(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:831)
```
	
	
Mysql online..

**Comment by Hopefuls** [comment]
Please provide more logs related to advanced an, such as on start. With this information you have provided we can't try to check what the issue is

**Comment by ibrahim12651** [comment]
> Please provide more logs related to advanced an, such as on start. With this information you have provided we can't try to check what the issue is

There was only this in the log.

**Comment by ibrahim12651** [comment]
MySQL settings are correct

![image](https://github.com/DevLeoko/AdvancedBan/assets/39805679/2511546c-0475-4dca-86d9-37aace7f016a)

**Comment by Hopefuls** [comment]
> MySQL settings are correct
> 
> ![image](https://private-user-images.githubusercontent.com/39805679/292665862-2511546c-0475-4dca-86d9-37aace7f016a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDM0Mjc1NzcsIm5iZiI6MTcwMzQyNzI3NywicGF0aCI6Ii8zOTgwNTY3OS8yOTI2NjU4NjItMjUxMTU0NmMtMDQ3NS00ZGNhLTg2ZDktMzdhYWNlN2YwMTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI0VDE0MTQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY4MGM4ZDFjMGE0MjAzNzIyZjEwNTIzNmE5NDk2YWQ5ZjhjZDA1YmI2MTQ2ZDc0YTExNTE4ZGY4YTVhOTZmYzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.S1Zu9wpMrqWQyemg9VL6lKrVnubXYfobMf7G0J2uVDo)

According to this, your MySQL credentials are incorrect. Please ensure that you've set the correct credentials and possibly grants within your MySQL Database and that your server is trying to connect to the correct one. There's a few tutorials on how to do so.

**Comment by ibrahim12651** [comment]
fix.
